In [1]:
import numpy as np

In [38]:
a1=np.array([1,2,3])
a1.ndim,a1.shape,type(a1),a1.size,a1.dtype

(1, (3,), numpy.ndarray, 3, dtype('int32'))

In [34]:
a2=np.array([[1,2,3],[1,2,3],[1,2,3],[1,2,3]])
a2.ndim,a2.shape

(2, (4, 3))

In [32]:
a3=np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
a3.ndim,a3.shape,a3

(3,
 (2, 2, 3),
 array([[[1, 2, 3],
         [1, 2, 3]],
 
        [[1, 2, 3],
         [1, 2, 3]]]))

In [42]:
import pandas as pd
df3=pd.DataFrame(a2)
df3

0  1  2
0  1  2  3
1  1  2  3
2  1  2  3
3  1  2  3

In [47]:
ones=np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [54]:
zeros=np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [55]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [59]:
np.random.randint(0,10,size=(7,2))

array([[6, 4],
       [6, 0],
       [7, 3],
       [8, 0],
       [4, 2],
       [2, 5],
       [1, 8]])

In [61]:
np.random.rand(3,5)

array([[0.82333052, 0.9683629 , 0.08852302, 0.29794114, 0.35714454],
       [0.81941973, 0.45875754, 0.43657219, 0.96948853, 0.18325847],
       [0.9708653 , 0.83296409, 0.5854588 , 0.74932822, 0.87385463]])

In [62]:
np.random.random((3,5))

array([[0.7081005 , 0.56750628, 0.04374415, 0.90831961, 0.12177765],
       [0.17345541, 0.93834089, 0.28794407, 0.63205412, 0.05419879],
       [0.24877835, 0.67688929, 0.79376182, 0.44322658, 0.76388949]])

In [63]:
np.random.seed(42)
np.random.randint(0,10,size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [68]:
a5=np.random.randint(1,10,size=(3,7))
a5,np.unique(a5)

(array([[2, 5, 8, 9, 9, 1, 9],
        [7, 9, 8, 1, 8, 8, 3],
        [1, 8, 3, 3, 1, 5, 7]]),
 array([1, 2, 3, 5, 7, 8, 9]))

In [69]:
a5[0]

array([2, 5, 8, 9, 9, 1, 9])

In [71]:
a5[:2]

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3]])

In [3]:
a6=np.random.randint(0,10,size=(3,5))
a6

array([[1, 5, 5, 7, 4],
       [4, 6, 1, 7, 0],
       [7, 3, 0, 3, 9]])

In [76]:
a7=np.ones((3,5))

In [77]:
a6+a7

array([[ 1.,  3.,  5.,  3.,  1.],
       [ 5., 10.,  7.,  7.,  9.],
       [10., 10.,  3.,  7.,  1.]])

In [15]:
a8=np.ones((3,5))
a8

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [82]:
a8.shape,a7.shape

((3, 5), (3, 5))

In [83]:
a8-a7

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [85]:
np.subtract(a8,a7)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
a6 * a8

array([[1., 5., 5., 7., 4.],
       [4., 6., 1., 7., 0.],
       [7., 3., 0., 3., 9.]])

In [6]:
np.multiply(a6 ,a8)

array([[1., 5., 5., 7., 4.],
       [4., 6., 1., 7., 0.],
       [7., 3., 0., 3., 9.]])

In [8]:
a6**2

array([[ 1, 25, 25, 49, 16],
       [16, 36,  1, 49,  0],
       [49,  9,  0,  9, 81]])

In [10]:
np.square(a6)

array([[ 1, 25, 25, 49, 16],
       [16, 36,  1, 49,  0],
       [49,  9,  0,  9, 81]])

In [12]:
np.mean(a6),np.max(a6),np.min(a6),np.std(a6),np.var(a6)

(4.133333333333334, 9, 0, 2.704728370013439, 7.315555555555554)

In [13]:
a8.reshape(3,5,1)

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [17]:
#a8.T
a8.transpose()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.random.seed(0)
a1=np.random.randint(0,10,size=(3,3))
a2=np.random.randint(0,10,size=(3,2))

In [20]:
a1@a2

array([[ 44,  38],
       [126,  86],
       [ 58,  63]])

In [21]:
a1.dot(a2)

array([[ 44,  38],
       [126,  86],
       [ 58,  63]])

In [38]:
np.random.seed(1)
a3=np.random.randint(0,10,size=(4,3))
a4=np.random.randint(0,10,size=(4,3))
a3,a4

(array([[5, 8, 9],
        [5, 0, 0],
        [1, 7, 6],
        [9, 2, 4]]),
 array([[5, 2, 4],
        [2, 4, 7],
        [7, 9, 1],
        [7, 0, 6]]))

In [24]:
a3.dot(a4.T)

array([[ 43,  51,  55,  72],
       [ 89, 130,  76, 164],
       [ 66,  67,  39,  85],
       [ 94, 115,  69, 146]])

In [27]:
a3>a4,a3>=a4

(array([[False, False,  True],
        [False, False,  True],
        [False,  True, False],
        [False, False, False]]),
 array([[False, False,  True],
        [False,  True,  True],
        [False,  True, False],
        [False, False, False]]))

In [28]:
a3>7

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False]])

In [29]:
a3==a4

array([[False, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False]])

In [31]:
np.sort(a3)

array([[0, 3, 5],
       [3, 7, 9],
       [2, 3, 5],
       [4, 6, 7]])

In [39]:
a3,np.argsort(a3)

(array([[5, 8, 9],
        [5, 0, 0],
        [1, 7, 6],
        [9, 2, 4]]),
 array([[0, 1, 2],
        [1, 2, 0],
        [0, 2, 1],
        [1, 2, 0]], dtype=int64))

In [40]:
np.argmin(a3),np.argmax(a3)

(4, 2)

In [41]:
np.argmin(a3,axis=0)

array([2, 1, 1], dtype=int64)

In [43]:
np.random.randn(10,5)

array([[ 0.04221375,  0.58281521, -1.10061918,  1.14472371,  0.90159072],
       [ 0.50249434,  0.90085595, -0.68372786, -0.12289023, -0.93576943],
       [-0.26788808,  0.53035547, -0.69166075, -0.39675353, -0.6871727 ],
       [-0.84520564, -0.67124613, -0.0126646 , -1.11731035,  0.2344157 ],
       [ 1.65980218,  0.74204416, -0.19183555, -0.88762896, -0.74715829],
       [ 1.6924546 ,  0.05080775, -0.63699565,  0.19091548,  2.10025514],
       [ 0.12015895,  0.61720311,  0.30017032, -0.35224985, -1.1425182 ],
       [-0.34934272, -0.20889423,  0.58662319,  0.83898341,  0.93110208],
       [ 0.28558733,  0.88514116, -0.75439794,  1.25286816,  0.51292982],
       [-0.29809284,  0.48851815, -0.07557171,  1.13162939,  1.51981682]])

In [52]:
np.linspace(1,50,5)

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])